### PR TITLE
Admin App Permission Management - Roles

### PR DESCRIPTION
**Pull request by birdofpreyru**

### CODE REVIEW

**Comment by huangqun** [comment]
@birdofpreyru please grant me access to your repo so I can merge locally and test it before accepting the PR. Thanks!

**Comment by huangqun** [comment]
Never mind, looks like I have access already.

**Comment by huangqun** [comment]
@birdofpreyru ok, new issue. I just tried to test this with real API and here's what I get: 
topcoder platform - support app 2017-05-14 23-08-09

The whole page seems to have frozen too. Could you please take a look and see if you can figure out what's wrong?

**Comment by birdofpreyru** [comment]
@huangqun I'm not sure about the exact cause of this issue, but my first guess is in the comment above.

**Comment by huangqun** [comment]
@birdofpreyru which comment were you referring to? I cannot find another comment from you on this PR.

Thanks!

**Comment by birdofpreyru** [comment]
@huangqun I've commented on a line in diff tab of this PR, and now this screen looks to me like this (includes that comment):
scr-17
Probably, I have to press `Submit review` button there to make it visible to everybody... I'll try now :)

**Comment by huangqun** [comment]
@birdofpreyru Sorry I didn't get a notification for that, I think you had to @  me so I can get a notification.

I'm testing it now.

**Comment by huangqun** [comment]
@birdofpreyru the freezing issue seems to be fixed but there are still a couple issues:
1. How do I delete a role?
2. Why does this keep showing `loading` and I don't think we have an API to list the assigned users yet?

http://take.ms/8Mcaof

**Comment by birdofpreyru** [comment]
Does it says something in console? It is supposed to load user handles into the spot where it shows `loading` at your screenshot. And each user handle there will have a red cross icon next to it to de-assign the role.

If there is no errors in the console, try to go to `permission_management.controller.js`, search for `vm.users[userId] = ` (there are two lines with such assignment), and try to enforce AngularJS to re-render related staff (adding after that line `vm.users = vm.users;` should do it, I guess).

**Comment by huangqun** [comment]
The problem is, what API you are using to get the list of users that have a specific role? I think that's part that breaks it. We do not have an API for that yet so we have to manually enter a handle and hit an Unassign button (similar to the Assign process), and the UI should tell the user whether that succeeds or not.

**Comment by birdofpreyru** [comment]
`/v3/roles/:roleId?fields=subjects`
In docs it was `/v3/roles/:roleId/subjects`, but at least one of the reviewers required to change it to `?fields=subjects`, saying that it is how it actually implemented in Java code for the backend. I'm not that good in Java, so I've just followed his request.

**Comment by huangqun** [comment]
No, that's not working and we can't follow that, could you please update your code to do the following?
1. Fix the issue you mentioned in your commit comment
2. Removed the section that shows Assigned Users because we really don't have an API for that yet.
3. Change this part to have two buttons: Assign and Unassign, and change the label `Assign User` to `User Handle`: 
image

We can pay another $100 for these changes, thanks!

**Comment by huangqun** [comment]
The UI should show a message to the user whether the Assign / Unassign operation succeeds or fails, with a meaningful message.

I'm closing this PR for now, please pull the latest code again since I'm merging another change in now.

**Pull request closed without merging**
