### PR TITLE
challenge #30057919 - 48H ADMIN APP - GROUP MEMBERSHIP MANAGEMENT

### PR DESCRIPTION
**Pull request by maxceem**
This pull request already contains Final Fixes 2. I do it now to make it faster, in case Final Fixes 2 would be accepted.

### CODE REVIEW

**Comment by huangqun** [comment]
@maxceem a few minor items that I hope you can fix:
1. On groups page, make the name clickable just like the id
2. The `Add Members` page need a `Back` button too

**Comment by maxceem** [comment]
Sure.
2. The Add Members page need a Back button too
There is a "Cancel" button http://joxi.ru/LVm6jNzUBwOYmZ similar to other pages like "New Billing Account" http://joxi.ru/LQ2Kkw4Sz5n12j
Should I remove it and put the "Back" button at the top instead?

**Comment by huangqun** [comment]
@maxceem ok, we can keep that as is.

**Comment by maxceem** [comment]
Great, I've already made a commit for clickable group names.

**Pull request merged**
